### ISSUE TITLE
ComponentsElectron needs update to latest ASP.NET Core 3.0 preview

### ISSUE THREAD

**Issue by stil** [aspnet/AspLabs#187]
After upgrading .NET Core SDK from preview 3 to preview 4, I can no longer build the project.

`dotnet build` output

```
Copyright (C) Microsoft Corporation. All rights reserved.

  Restore completed in 387.69 ms for C:\Users\user\Desktop\SampleApp\SampleApp.csproj.
C:\Program Files\dotnet\sdk\3.0.100-preview4-011223\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.RuntimeIdentifierInference.targets(151,5): message NETSDK1057: You are using a preview version of .NET Core. See: https://aka.ms/dotnet-core-preview [C:\Users\user\Desktop\SampleApp\SampleApp.csproj]
Startup.cs(1,39): error CS0234: The type or namespace name 'Builder' does not exist in the namespace 'Microsoft.AspNetCore.Components' (are you missing an assembly reference?) [C:\Users\user\Desktop\SampleApp\SampleApp.csproj]
obj\Debug\netcoreapp3.0\RazorDeclaration\Shared\MainLayout.cshtml.g.cs(16,31): error CS0246: The type or namespace name 'LayoutComponentBase' could not be found (are you missing a using directive or an assembly reference?) [C:\Users\user\Desktop\SampleApp\SampleApp.csproj]
obj\Debug\netcoreapp3.0\RazorDeclaration\Pages\_ViewImports.cshtml.g.cs(16,69): error CS0246: The type or namespace name 'MainLayout' could not be found (are you missing a using directive or an assembly reference?) [C:\Users\user\Desktop\SampleApp\SampleApp.csproj]
obj\Debug\netcoreapp3.0\RazorDeclaration\Shared\MainLayout.cshtml.g.cs(19,33): error CS0115: 'MainLayout.BuildRenderTree(RenderTreeBuilder)': no suitable method found to override [C:\Users\user\Desktop\SampleApp\SampleApp.csproj]
Startup.cs(12,31): error CS0246: The type or namespace name 'IComponentsApplicationBuilder' could not be found (are you missing a using directive or an assembly reference?) [C:\Users\user\Desktop\SampleApp\SampleApp.csproj]

Build FAILED.

Startup.cs(1,39): error CS0234: The type or namespace name 'Builder' does not exist in the namespace 'Microsoft.AspNetCore.Components' (are you missing an assembly reference?) [C:\Users\user\Desktop\SampleApp\SampleApp.csproj]
obj\Debug\netcoreapp3.0\RazorDeclaration\Shared\MainLayout.cshtml.g.cs(16,31): error CS0246: The type or namespace name 'LayoutComponentBase' could not be found (are you missing a using directive or an assembly reference?) [C:\Users\user\Desktop\SampleApp\SampleApp.csproj]
obj\Debug\netcoreapp3.0\RazorDeclaration\Pages\_ViewImports.cshtml.g.cs(16,69): error CS0246: The type or namespace name 'MainLayout' could not be found (are you missing a using directive or an assembly reference?) [C:\Users\user\Desktop\SampleApp\SampleApp.csproj]
obj\Debug\netcoreapp3.0\RazorDeclaration\Shared\MainLayout.cshtml.g.cs(19,33): error CS0115: 'MainLayout.BuildRenderTree(RenderTreeBuilder)': no suitable method found to override [C:\Users\user\Desktop\SampleApp\SampleApp.csproj]
Startup.cs(12,31): error CS0246: The type or namespace name 'IComponentsApplicationBuilder' could not be found (are you missing a using directive or an assembly reference?) [C:\Users\user\Desktop\SampleApp\SampleApp.csproj]
    0 Warning(s)
    5 Error(s)

Time Elapsed 00:00:08.11
PS C:\Users\user\Desktop\SampleApp>
```

**Comment by Eilon** [comment]
Tagging @SteveSandersonMS / @danroth27

**Comment by SteveSandersonMS** [comment]
Fixed in #188

**Comment by Difference** [comment]
![image](https://user-images.githubusercontent.com/142553/57478664-d032d380-729b-11e9-9777-9e7a9fcaa878.png)
I still get this with latest VS Preview 16.1.0, Preview3 and dotnet core 3 Preview5

**Comment by stil** [comment]
I can confirm, the issue still occurs on preview 5

**Comment by danroth27** [comment]
The sample wasn't updated yet and to properly update the sample we need to publish the Microsoft.AspNetCore.Components.Electron package to one of the dev feeds.

**Comment by danroth27** [comment]
@mkArtakMSFT

**Comment by dougbu** [comment]
@aspnet/build the ask here is to push just one package to a publicly-accessible feed and a blob feed would be fine. We don't need to execute the existing aspnet-AspLabs release pipeline or otherwise push to aspnetcore-dev on MyGet in particular.

**Comment by danroth27** [comment]
@dougbu It's probably sufficient if we just manually publish the required package to the blazor-dev feed (once we get a build).

**Comment by dougbu** [comment]
@danroth27 @pranavkm @SteveSandersonMS what work remains here and who is on point to do that work? That is, who should be manually updating https://dotnet.myget.org/feed/blazor-dev/package/nuget/Microsoft.AspNetCore.Components.Electron (which is still 5 months out of date)? (I don't have the tokens needed to do anything here.)

/cc @mkArtakMSFT

**Comment by SteveSandersonMS** [comment]
@dougbu The remaining work is updating https://github.com/aspnet/AspLabs/pull/192, though presumably it's best to wait until preview 7 ships now rather than being out of date straight away. Then we can push the updated package, which I and @danroth27 both have permissions to do.

**Comment by JunTaoLuo** [comment]
@SteveSandersonMS now that preview 7 is out can this be closed?

**Comment by SteveSandersonMS** [comment]
I'll update the issue title.

**Comment by julienGrd** [comment]
Hello guys, now the .net core 3 is release, it can be good to update the packages ? With the sample im still in preview3, and surprisely i can't update the package by myself.

thanks !

**Comment by kant2002** [comment]
@SteveSandersonMS if you can publish latest `Microsoft.AspNetCore.Components.Electron` to aspnetcore-dev feed, or whenether you find appropriate. Currently SampleApps does not working with RTM bits, but TestApp works fine, which means, they should be dragged along to the test project, which is contrary to README.md.

Given that this repo highlighted in
https://devblogs.microsoft.com/aspnet/blazor-server-in-net-core-3-0-scenarios-and-performance/
can you give it your caring touch?

**Comment by snow-jallen** [comment]
Maybe the title of this could even be "CompenentsElectron needs update to final RTM ASP.NET Core 3.0".  I spun my wheels for too long this morning wondering why the sample wouldn't compile before I found this issue.  :(

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
We're closing this issue as we're using `dotnet/AspNetCore` repo's issue tracker instead.
If you think this issue is still relevant, please file a new issue in that repo, so the team can triage it.
